# ===============================================================
# 
# Release under GPLv-3.0.
# 
# @file    Makefile.am
# @brief   
# @author  gnsyxiang <gnsyxiang@163.com>
# @date    04/09 2026 10:04
# @version v0.0.1
# 
# @since    note
# @note     note
# 
#     change log:
#     NO.     Author              Date            Modified
#     00      zhenquan.qiu        04/09 2026      create the file
# 
#     last modified: 04/09 2026 10:04
# ===============================================================

# ------------------
# defining variables
# ------------------
_dist_file_com  =

# ---------------
# make dist files
# ---------------
_dist_file_com  +=

EXTRA_DIST      = $(_dist_file_com)

